name: GitHub Contribution Graph Form
description: Submit your desired GitHub Contribution Graph via below form
title: "GitHub Contribution Graph Application Form"
labels: ["application-form", "invalid"]
assignees: []
body:
  - type: textarea
    id: contribution-graph
    attributes:
      label: Customize your GitHub Contribution pattern
      description: You can create contribution graph on your own.
      placeholder: Mark contribution as 🟢 or inaction as ⚪.
      value: |
        | 1| 2| 3| 4| 5| 6| 7| 8| 9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|
        |--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|
        |⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|
        |🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|
        |⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|
        |🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|
        |⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|
        |🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|
        |⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|🟢|⚪|
    validations:
      required: true
  - type: dropdown
    id: pattern
    attributes:
      label: Which pattern do you want for GitHub Contribution Graph to be?
      multiple: false
      options:
        - Chessboard
        - Love
        - Star
        - GitHub
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
