name: Beautify my GitHub Contribution 

on:
  push:
    branches:
      - lucetre-patch-1
  workflow_dispatch:

jobs:
  update-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "MY_DATE=$(date +%Y-%m-%d-%H:%M:%s)" >> $GITHUB_ENV
        
      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.LINKEDART_GH_PAT }}
        with:
          header: "Hey, guys! 👋"
          subhead: "Contribution log for beautifying your GitHub contribution graph."
          footer: ${{ env.MY_DATE }} - ${{ github.actor }} - ${{ github.triggering_actor }} - ${{ github.event_name }}
          path: CONTRIBUTION.md
          repoCount: 0
