name: Issue Author Assignment

on:
  issues:
    types: [ opened, edited ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Add assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          assignees: ${{ github.actor }}

  update-label-as-valid:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'xxx') == true
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          labels: 'valid'
      - name: Remove labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          labels: 'invalid'

  update-label-as-invalid:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'xxx') == false
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          labels: 'invalid'
      - name: Remove labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          labels: 'valid'
  
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Hello @${{ github.event.issue.user.login }}. Add some comments.
            你好 @${{ github.event.issue.user.login }}。巴拉巴拉。
          emoji: '+1,heart'
  
