name: Issue Author Assignment

on:
  issues:
    types: [ opened, edited ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Add assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          assignees: ${{ github.actor }}
