name: Register GitHub Secrets via Issue
on:
  push:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/lucetre/beautify-github-contribution/actions/secrets
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/lucetre/beautify-github-contribution/actions/secrets/public-key
        env:
          GITHUB_TOKEN: ${{ secrets.LUCETRE_GH_PAT }}
