name: Register GitHub Secrets via Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      SECRET_NAME:
        description: 'Secrete Name'
        required: true
      SECRET_VALUE:
        description: 'Secret Value'
        required: true

jobs:
  register-github-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Add mask to SECRET_VALUE
        run: |
          SECRET_VALUE=$(cat $GITHUB_EVENT_PATH | jq '.inputs.SECRET_VALUE' | sed 's/"//g' )
          echo "::add-mask::$SECRET_VALUE"
          echo SECRET_VALUE=$SECRET_VALUE >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        with:
          python-version: '3.9'

      - name: Register secret - ${{ inputs.SECRET_NAME }}
        run: |
          bash tools/register_github_secret.sh
        env:
          SECRET_NAME: ${{ inputs.SECRET_NAME }}
          SECRET_VALUE: ${{ env.SECRET_VALUE }}
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_PAT }}
