name: Register GitHub Secrets via Issue
on:
  push:

jobs:
  encrypt-github-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        with:
          python-version: '3.9'

      - run: |
          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
          bash tools/register_github_secret.sh
        env:
          SECRET_NAME: "TEST_SECRET"
          SECRET_VALUE: "this is new"
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_PAT }}
