name: Beautify my GitHub Contribution 
on:
  push:
  # schedule:
  #   - cron: '5 0 * * *'

jobs:
  contribute:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
          date +%Y/%m/%d-%H:%M:%S
          # echo "TODAY=$(date +%Y/%m/%d)" >> $GITHUB_ENV
          echo "TODAY=test" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - run: |
          while read contributor; do
            echo "USER_PAT_$contributor"
            echo ${{ secrets[format('USER_PAT_{0}', $contributor)] }} | sed 's/./& /g'
          done <scheduler/${{ env.TODAY }}/CONTRIBUTORS

      - run: |
          CONTRIBUTOR=linkedart-snu
          str=$(cat "scheduler/${{ env.TODAY }}/CONTRIBUTORS" | grep $CONTRIBUTOR | tr -d '[:space:]')

          if [[ $str == $CONTRIBUTOR ]]; then
            echo "CONTRIBUTION_TRIGGER=true" >> $GITHUB_ENV
          else
            echo "CONTRIBUTION_TRIGGER=false" >> $GITHUB_ENV
          fi

      # - name: Update GitHub Profile README
      #   uses: theboi/github-update-readme@v1.0
      #   if: env.CONTRIBUTION_TRIGGER == 'true'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.LINKEDART_GH_PAT }}
      #   with:
      #     header: "Hey, guys! 👋"
      #     subhead: "Contribution log for beautifying your GitHub contribution graph."
      #     footer: ${{ env.TODAY }} - ${{ github.actor }} - ${{ github.triggering_actor }} - ${{ github.event_name }}
      #     path: CONTRIBUTION.md
      #     repoCount: 0
