name: Validate Application Form

on:
  issues:
    types: [ opened, edited, reopened, labeled, unlabeled, unassigned ]

jobs:
  update-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Set label as valid
        if: contains(github.event.issue.body, 'xxx') == true
        run: echo "ISSUE_LABEL=valid" >> $GITHUB_ENV
        
      - name: Set label as invalid
        if: contains(github.event.issue.body, 'xxx') == false
        run: echo "ISSUE_LABEL=invalid" >> $GITHUB_ENV
        
      - name: Update issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          title: 'GitHub Contribution Graph Application Form - ${{ github.actor }}'
          body: ${{ github.event.issue.body }}
          update-mode: 'replace'
          labels: 'application-form,${{ env.ISSUE_LABEL }}'
          assignees: '${{ github.actor }}'
          emoji: 'rocket'
  
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome comment
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Welcome, Contributor @${{ github.event.issue.user.login }}!
            Our bot will soon validate your form and provide preview via issue comments below.
          emoji: 'eyes,heart'

      - name: Valid comment
        if: env.ISSUE_LABEL == 'valid' && github.event.action != 'opened' && github.event.action != 'reopened'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Hey @${{ github.event.issue.user.login }},
            Your application form is correctly validated. Press Checkbox 'Start your GitHub Contribution' above to deploy.
          emoji: '+1,laugh,hooray'

      - name: Invalid comment
        if: env.ISSUE_LABEL == 'invalid' && github.event.action != 'opened' && github.event.action != 'reopened'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Hello @${{ github.event.issue.user.login }},
            Looks like your application form is invalid. Please check it again.
          emoji: '-1,confused'
  