name: Validate Application Form

on:
  issues:
    types: [ opened, edited, reopened, unassigned ]

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ ToJson(github.event.issue) }}
      - name: Lock issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'lock-issue'
      
      - name: Set label as validating
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          labels: 'application-form,validating'

      - name: Set label as valid
        if: contains(github.event.issue.body, 'xxx') == true
        run: |
          echo "ISSUE_LABEL=valid" >> $GITHUB_ENV
          DEPLOY=$(echo '${{ github.event.issue.body }}' | grep 'Let my GitHub bot' | grep -oP '(?<=\[).*?(?=\])')
          [[ ! -z "${DEPLOY// /}" ]] && (echo "ISSUE_LABEL=valid,shipped-to-deploy" >> $GITHUB_ENV)
        
      - name: Set label as invalid
        if: contains(github.event.issue.body, 'xxx') == false
        run: echo "ISSUE_LABEL=invalid" >> $GITHUB_ENV
        
      - name: Update issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          title: 'GitHub Contribution Graph Application Form - `${{ github.event.issue.user.login }}`'
          body: ${{ github.event.issue.body }}
          update-mode: 'replace'
          labels: 'application-form,${{ env.ISSUE_LABEL }}'
          assignees: '${{ github.event.issue.user.login }}'
          emoji: 'rocket'

    outputs:
      issue-label: ${{ env.ISSUE_LABEL }}
  
  create-comment:
    needs: validate-issue
    runs-on: ubuntu-latest
    env:
      ISSUE_LABEL: ${{ needs.validate-issue.outputs.issue-label }}
    steps:
      - name: Unlock issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'unlock-issue'

      - name: Welcome comment
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Welcome, Contributor @${{ github.event.issue.user.login }}!
            Our bot will soon validate your form and provide preview via issue comments below.
          emoji: 'eyes,heart'

      - uses: actions/checkout@v3
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        
      - uses: actions/setup-python@v4
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        with:
          python-version: '3.9'

      - name: Generate contribution graph
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        run: |
          echo '${{ github.event.issue.body }}' | sed '/^$/d' | sed '1,/```/d' | sed '/```/,$d' > tools/contribution/graph.txt
          cat tools/contribution/graph.txt

          pip install numpy
          python tools/create_contribution_md.py

          cat tools/contribution/preview.md | sed -r 's/\:white_circle\:/⚪/g' | sed -r 's/\:green_circle\:/🟢/g'
          PREVIEW=$(cat tools/contribution/preview.md | sed -r 's/\:white_circle\:/⚪/g' | sed -r 's/\:green_circle\:/🟢/g')

          echo "PREVIEW<<EOF" >> $GITHUB_ENV
          echo "$PREVIEW" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          CONTRIBUTION_GRAPH=$(cat tools/contribution/graph.md)
          echo "CONTRIBUTION_GRAPH<<EOF" >> $GITHUB_ENV
          echo "$CONTRIBUTION_GRAPH" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Valid comment
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Awesome @${{ github.event.issue.user.login }}! Your application form has been correctly validated.
            Press above checkbox **Start my GitHub Contribution** to deploy.
            ```
            ${{ env.PREVIEW }}
            ```
          emoji: '+1,laugh,hooray'

      - name: Invalid comment
        if: contains(env.ISSUE_LABEL, 'invalid') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Uh-oh @${{ github.event.issue.user.login }},
            Looks like your application form is invalid. Please check it again.
          emoji: '-1,confused'

      - name: Valid comment
        if: contains(env.ISSUE_LABEL, 'shipped-to-deploy') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Congratulations @${{ github.event.issue.user.login }}! Your contribution graph has been shipped to deploy.
            ${{ env.CONTRIBUTION_GRAPH }}
          emoji: 'rocket,heart'

      - name: Valid comment
        if: contains(env.ISSUE_LABEL, 'shipped-to-deploy') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Congratulations @${{ github.event.issue.user.login }}! Your contribution graph has been shipped to deploy.
            ${{ env.CONTRIBUTION_GRAPH }}
          emoji: 'rocket,heart'
      
      - name: Close issue
        if: contains(env.ISSUE_LABEL, 'shipped-to-deploy') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'

