name: Validate Application Form

on:
  issues:
    types: [ opened, edited ]

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome comment
        if: github.event.action == 'opened'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Welcome, Contributor @${{ github.event.issue.user.login }}!
            Our bot will soon validate your form and provide preview via issue comments below.
          emoji: 'eyes,heart'

      - name: Lock issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'lock-issue'
      
      - name: Set label as validating
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          labels: 'application-form,validating'

      - name: Add mask to ISSUE_BODY
        run: |
          ISSUE_BODY=$(cat $GITHUB_EVENT_PATH | jq '.issue.body' | sed 's/"//g' )
          echo "::add-mask::$ISSUE_BODY"
          echo ISSUE_BODY=$ISSUE_BODY >> $GITHUB_ENV

      - uses: actions/checkout@v3
        if: github.event.action == 'opened'

      - name: Register GitHub PAT of the user
        if: github.event.action == 'opened'
        run: |
          USER_PAT=$(echo -e '${{ env.ISSUE_BODY }}' | sed '/^$/d' | sed '1,/GitHub PAT/d' | sed '/Start my/,$d')
          gh workflow run register-github-secrets.yaml -f SECRET_NAME=USER_PAT_${{ github.event.issue.user.login }} -f SECRET_VALUE=$USER_PAT
          
          echo 'ISSUE_BODY<<EOF' >>$GITHUB_ENV
          echo -e '${{ env.ISSUE_BODY }}' | sed "/GitHub PAT/,/$USER_PAT/d" >>$GITHUB_ENV
          echo 'EOF' >>$GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set label as valid
        if: contains(github.event.issue.body, 'xxx') == true
        run: |
          echo "ISSUE_LABEL=valid" >> $GITHUB_ENV
          DEPLOY=$(echo -e '${{ env.ISSUE_BODY }}' | grep 'Let my GitHub bot' | grep -oP '(?<=\[).*?(?=\])')
          if [[ ! -z "${DEPLOY// /}" ]]
          then
            echo "ISSUE_LABEL=valid,shipped-to-deploy" >> $GITHUB_ENV
          fi

      - name: Set label as invalid
        if: contains(github.event.issue.body, 'xxx') == false
        run: echo "ISSUE_LABEL=invalid" >> $GITHUB_ENV

      - name: Update issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          title: 'GitHub Contribution Graph Application Form - `${{ github.event.issue.user.login }}`'
          body: "${{ env.ISSUE_BODY }}"
          update-mode: 'replace'
          labels: 'application-form,${{ env.ISSUE_LABEL }}'
          assignees: '${{ github.event.issue.user.login }}'
          emoji: 'rocket'

    outputs:
      issue-label: ${{ env.ISSUE_LABEL }}
  
  create-comment:
    needs: validate-issue
    runs-on: ubuntu-latest
    env:
      ISSUE_LABEL: ${{ needs.validate-issue.outputs.issue-label }}
    steps:
      - name: Add mask to ISSUE_BODY
        run: |
          ISSUE_BODY=$(cat $GITHUB_EVENT_PATH | jq '.issue.body' | sed 's/"//g' )
          echo "::add-mask::$ISSUE_BODY"
          echo ISSUE_BODY=$ISSUE_BODY >> $GITHUB_ENV

      - name: Unlock issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'unlock-issue'

      - uses: actions/checkout@v3
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        
      - uses: actions/setup-python@v4
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        with:
          python-version: '3.9'

      - name: Generate contribution graph
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        run: |
          echo -e '${{ env.ISSUE_BODY }}' | sed '/^$/d' | sed '1,/```/d' | sed '/```/,$d' > tools/contribution/graph.txt
          cat tools/contribution/graph.txt

          pip install numpy
          python tools/create_contribution_md.py

          cat tools/contribution/preview.md | sed -r 's/\:white_circle\:/⚪/g' | sed -r 's/\:green_circle\:/🟢/g'
          PREVIEW=$(cat tools/contribution/preview.md | sed -r 's/\:white_circle\:/⚪/g' | sed -r 's/\:green_circle\:/🟢/g')

          echo "PREVIEW<<EOF" >> $GITHUB_ENV
          echo "$PREVIEW" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          CONTRIBUTION_GRAPH=$(cat tools/contribution/deploy.md)
          echo "CONTRIBUTION_GRAPH<<EOF" >> $GITHUB_ENV
          echo "$CONTRIBUTION_GRAPH" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Valid comment
        if: contains(env.ISSUE_LABEL, 'invalid') == false
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Awesome @${{ github.event.issue.user.login }}! Your application form has been correctly validated.
            Press above checkbox **Start my GitHub Contribution** to deploy.
            ```
            ${{ env.PREVIEW }}
            ```
          emoji: '+1,laugh,hooray'

      - name: Invalid comment
        if: contains(env.ISSUE_LABEL, 'invalid') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Uh-oh @${{ github.event.issue.user.login }},
            Looks like your application form is invalid. Please check it again.
          emoji: '-1,confused'

      - name: Valid comment
        if: contains(env.ISSUE_LABEL, 'shipped-to-deploy') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Congratulations @${{ github.event.issue.user.login }}! Your contribution graph has been shipped to deploy.
            ${{ env.CONTRIBUTION_GRAPH }}
          emoji: 'rocket,heart'
      
      - name: Close issue
        if: contains(env.ISSUE_LABEL, 'shipped-to-deploy') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          close-reason: completed

      - name: Schedule shipped contribution
        if: contains(env.ISSUE_LABEL, 'shipped-to-deploy') == true
        run: |
          python tools/schedule_contribution.py
          tree scheduler
        env:
          CONTRIBUTOR: ${{ github.event.issue.user.login }}

      - uses: EndBug/add-and-commit@v9
        if: contains(env.ISSUE_LABEL, 'shipped-to-deploy') == true
        with:
          default_author: github_actions
          message: '[Issue #${{ github.event.issue.number }}] Schedule contribution for `${{ github.event.issue.user.login }}`'
          add: 'scheduler --force'
